services:
  diagier_clinics_db:
    image: postgres:latest
    container_name: diagier_clinics_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: diagier_clinics_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - app-network

  api:
    build: .
    container_name: microservice_diagier_clinics
    environment:
      DB_HOST: diagier_clinics_db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - "8080:8080"
    volumes:
    - ./infrastructure/database/migrations:/app/infrastructure/database/migrations
    depends_on:
      - diagier_clinics_db
      - rabbitmq
    networks:
      - app-network
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
